# Generated by Django 4.1.3 on 2022-11-02 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='item',
        ),
    ]
