version: "3"

services:
  api:
    container_name: api
    build: .
    ports:
      - '8000:8000'
    links:
      - baseDatos

  baseDatos:
    container_name: baseDatos
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=semantica
      - POSTGRES_PASSWORD=semantica.2022
    ports:
      - '5432:5432'
    volumes:
      - baseDatos:/var/lib/postgresql/data

volumes:
  baseDatos:
    driver: local