version: "3"

services:
  api:
    container_name: api
    build: .
    ports:
      - '8000:8000'
    links:
      - postgresBaseDatos

  postgresBaseDatos:
    container_name: postgresBaseDatos
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgresBaseDatos:/var/lib/postgresql/data

volumes:
  postgresBaseDatos:
    driver: local